export const ADD_TODO = "ADD_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const CLEAR_ALL_TODO = "CLEAR_ALL_TODO"
export const MARK_AS_COMPLETED = "MARK_AS_COMPLETED"
export const IS_ADDING = "IS_ADDING"
export const IS_EDITING = "IS_EDITING"